version: '3.1'

services:
  mir-master-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: miruser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mir
    volumes:
    - ./pg/master/:/var/lib/postgresql/data/
  mir-master-solr:
    image: vzgreposis/mir-solr:master
    restart: always
    volumes:
    - ./solr/master/:/opt/solr-data
    environment:
      SOLR_HOME: /opt/solr-data
      LOG4J_FORMAT_MSG_NO_LOOKUPS: true
  mir-master:
    image: mycore/mir:master
    restart: always
    environment:
      APP_CONTEXT: mir-master
      JDBC_NAME: miruser
      JDBC_PASSWORD: mypassword
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql:\/\/mir-master-db:5432\/mir
      MCR_HOME: /root/.mycore/mir-master/
      SOLR_URL: http:\/\/mir-master-solr\:8983
      SOLR_CORE: mir
      MIR_FEATURES: "IIIFPresentation"
      LOG4J_FORMAT_MSG_NO_LOOKUPS: true
    volumes:
    - ./mir/master:/root/.mycore/mir-master/
    depends_on:
      - mir-master-db
      - mir-master-solr
    ports:
      - 8281:8080
      - 8282:8009
  mir-2021-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: miruser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mir
    volumes:
      - ./pg/2021/:/var/lib/postgresql/data/
  mir-2021-solr:
    image: vzgreposis/mir-solr:master
    restart: always
    volumes:
      - ./solr/2021/:/opt/solr-data
    environment:
      SOLR_HOME: /opt/solr-data
      LOG4J_FORMAT_MSG_NO_LOOKUPS: true
  mir-2021:
    image: mycore/mir:2021.06.1
    restart: always
    environment:
      APP_CONTEXT: mir
      JDBC_NAME: miruser
      JDBC_PASSWORD: mypassword
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql:\/\/mir-2021-db:5432\/mir
      MCR_HOME: /root/.mycore/mir/
      SOLR_URL: http:\/\/mir-2021-solr\:8983
      SOLR_CORE: mir
      MIR_FEATURES: "IIIFPresentation"
      LOG4J_FORMAT_MSG_NO_LOOKUPS: true
    volumes:
      - ./mir/2021:/root/.mycore/mir/
    depends_on:
      - mir-2021-db
      - mir-2021-solr
    ports:
      - 8283:8080
      - 8284:8009
